/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
       String getuser;
    public login() {
        initComponents();
        this.setBounds(450, 200, 400, 400);
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        Font f1 = new Font("candara",Font.PLAIN,15);
        Color c = new Color(51,51,51);
        usertext.setText("Enter Username");
        passtext.setText("Enter Password");
        
        usertext.setFont(f1);
        passtext.setFont(f1);
    
            usertext.setForeground(c);
        passtext.setForeground(c);
        
    usertext.setCaretPosition(0);
    passtext.setCaretPosition(0);
    

    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        usertext =  new javax.swing.JTextField();
        login = new javax.swing.JButton();
        passtext = new javax.swing.JPasswordField();
        error = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(34, 71, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users.png"))); // NOI18N

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(167, 222, 226));
        username.setText("Username:");

        password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(167, 222, 226));
        password.setText("Password:");

        usertext.setForeground(new java.awt.Color(0, 0, 0));
        usertext.setToolTipText("");
        usertext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usertext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usertextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usertextFocusLost(evt);
            }
        });
        usertext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usertextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usertextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usertextMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                usertextMouseReleased(evt);
            }
        });
        usertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertextActionPerformed(evt);
            }
        });
        usertext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usertextKeyReleased(evt);
            }
        });

        login.setBackground(new java.awt.Color(255, 153, 51));
        login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(0, 51, 51));
        login.setText("Login");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        passtext.setForeground(new java.awt.Color(51, 51, 51));
        passtext.setText("jPasswordField1");
        passtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passtextFocusLost(evt);
            }
        });
        passtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passtextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passtextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passtextMouseExited(evt);
            }
        });
        passtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passtextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passtextKeyTyped(evt);
            }
        });

        error.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        error.setForeground(new java.awt.Color(0, 153, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usertext, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(passtext))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usertext, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passtext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        try {
        if(usertext.getText().equals("") || usertext.getText().equals("Enter Username")){
       error.setText("Please enter your username");
Timer t  = new Timer(6000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
     error.setText("");
            }
        });
t.start();
       }
       else if(passtext.getText().equals("") || passtext.getText().equals("Enter Password")){
       error.setText("Kindly enter your password");
       Timer t  = new Timer(6000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
     error.setText("");
            }
        });
       t.start();
       }
       else{
            try{
        Class.forName("com.mysql.jdbc.Driver");
        String url ="jdbc:mysql://127.0.0.1:3306/shopace";
        Statement st;
        ResultSet rs;

        try (Connection conn = DriverManager.getConnection(url,"ecobank","efemena1")) {

                //conn = DriverManager.getConnection(url,"ecobank","efemena1");
                String checkuser = "select * from staff where username=? and password=?";
            
                
                PreparedStatement pst = conn.prepareStatement(checkuser);
           pst.setString(1, usertext.getText());
             pst.setString(2, passtext.getText());
                  
                rs = pst.executeQuery();
                
                
                while(rs.next()){
                    getuser = rs.getString("username");
                   Object[] options ={"Thanks"};
             
                final JOptionPane msg = new JOptionPane("Welcome staff "+getuser +" to ShopAce sales",JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
                msg.createToolTip();
                msg.setFont(new Font("Candara", Font.PLAIN , 16));
                final JDialog dlg  = msg.createDialog("Welcome " +getuser);
                dlg.setFont(new Font("Candara", Font.PLAIN , 16));
                dlg.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                msg.setBackground(new Color(207,208,210,200));
                dispose();
                
                Thread t = new Thread(new Runnable() {
                       @Override
                       public void run() {
                  Cms h = new Cms();
                  h.setVisible(true);
                dlg.setVisible(true);
                  h.setAlwaysOnTop(false);
h.login.setText(getuserText());               


                       }
                });
                t.start();
                    }
                
        }                
            } catch (Exception e) {
            }
       }
        
        } catch (Exception e) {
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_loginActionPerformed
String getuserText(){
String getu = getuser;

return getu;
}
    private void usertextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertextMouseEntered
     
    }//GEN-LAST:event_usertextMouseEntered

    private void passtextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passtextMouseEntered

    }//GEN-LAST:event_passtextMouseEntered

    private void usertextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertextMouseClicked

    }//GEN-LAST:event_usertextMouseClicked

    private void passtextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passtextMouseClicked
       
    }//GEN-LAST:event_passtextMouseClicked

    private void usertextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertextMouseExited
    
    }//GEN-LAST:event_usertextMouseExited

    private void passtextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passtextMouseExited
       
        
    }//GEN-LAST:event_passtextMouseExited

    private void usertextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertextMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextMouseReleased

    private void usertextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertextFocusLost
       if(usertext.getText().equals("")){
       usertext.setText("Enter Username");
       usertext.setForeground( new Color(51,51,51));
       }
    }//GEN-LAST:event_usertextFocusLost

    private void passtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passtextFocusLost
        
        if(passtext.getText().equals("")){
       passtext.setText("Enter Password");
       passtext.setForeground( new Color(51,51,51));
        }
        
    }//GEN-LAST:event_passtextFocusLost

    private void usertextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertextFocusGained
        if(usertext.getText().equals("Enter Username")){
       usertext.setText("");
       passtext.setForeground(new Color(93,95,95));
        }
    }//GEN-LAST:event_usertextFocusGained

    private void passtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passtextFocusGained
           if(passtext.getText().equals("Enter Password")){
       passtext.setText("");
       passtext.setForeground(new Color(93,95,95));
           }
    }//GEN-LAST:event_passtextFocusGained

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
       login.setBackground(new Color(174,250,129));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
       login.setBackground(new Color(255,153,51));
    }//GEN-LAST:event_loginMouseExited

    private void usertextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usertextKeyReleased

        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                
        try {
        if(usertext.getText().equals("") || usertext.getText().equals("Enter Username")){
       error.setText("Please enter your username");
Timer t  = new Timer(4000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
     error.setText("");
            }
        });
t.start();
       }
       else if(passtext.getText().equals("") || passtext.getText().equals("Enter Password")){
       error.setText("Kindly enter your password");
       Timer t  = new Timer(4000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
     error.setText("");
            }
        });
       t.start();
       }
       else{
            try{
        Class.forName("com.mysql.jdbc.Driver");
        String url ="jdbc:mysql://127.0.0.1:3306/shopace";
        Statement st;
        ResultSet rs;

        try (Connection conn = DriverManager.getConnection(url,"ecobank","efemena1")) {

                //conn = DriverManager.getConnection(url,"ecobank","efemena1");
                String checkuser = "select * from staff where username=? and password=?";
            
                
                PreparedStatement pst = conn.prepareStatement(checkuser);
           pst.setString(1, usertext.getText());
             pst.setString(2, Arrays.toString(passtext.getPassword()));
                  
                rs = pst.executeQuery();
                while(rs.next()){
                   String getuser1 = rs.getString("username");
                   Object[] options ={"Thanks"};
                   
                final JOptionPane msg = new JOptionPane("Welcome staff "+getuser1+" to ShopAce sales",JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
                msg.createToolTip();
                msg.setFont(new Font("Candara", Font.PLAIN , 16));
                final JDialog dlg  = msg.createDialog("Welcome " +getuser1);
                dlg.setFont(new Font("Candara", Font.PLAIN , 16));
                dlg.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                msg.setBackground(new Color(207,208,210,200));
                dispose();
                
                Thread t = new Thread(new Runnable() {
                       @Override
                       public void run() {
                    
                  Cms h = new Cms();
                
                  h.setVisible(true);
                dlg.setVisible(true);
                  h.setAlwaysOnTop(false);
h.login.setText(getuser1);                
                       }
                });
                t.start();
                    }
                
        }                
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            }
           
           
           
           
           
           
           
       }
        
        } catch (Exception e) {
        e.printStackTrace();
        }

                break;
        }
    }//GEN-LAST:event_usertextKeyReleased

    private void passtextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passtextKeyTyped
        
    }//GEN-LAST:event_passtextKeyTyped

    private void passtextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passtextKeyReleased
        
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                
        try {
        if(usertext.getText().equals("") || usertext.getText().equals("Enter Username")){
       error.setText("Please enter your username");
Timer t  = new Timer(6000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
     error.setText("");
            }
        });
t.start();
       }
       else if(passtext.getText().equals("") || passtext.getText().equals("Enter Password")){
       error.setText("Kindly enter your password");
       Timer t  = new Timer(6000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
     error.setText("");
            }
        });
       }
       else{
            try{
        Class.forName("com.mysql.jdbc.Driver");
        String url ="jdbc:mysql://127.0.0.1:3306/shopace";
        Statement st;
        ResultSet rs;

        try (Connection conn = DriverManager.getConnection(url,"ecobank","efemena1")) {

                //conn = DriverManager.getConnection(url,"ecobank","efemena1");
                String checkuser = "select * from staff where username=? and password=?";
            
                
                PreparedStatement pst = conn.prepareStatement(checkuser);
           pst.setString(1, usertext.getText());
             pst.setString(2, passtext.getText().toString());
                  
                rs = pst.executeQuery();
                  
                while(rs.next()){
                    String getuser = rs.getString("username");
                   Object[] options ={"Thanks"};
                   
                final JOptionPane msg = new JOptionPane("Welcome staff "+getuser+" to Covenant Plus CMS sales",JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
                msg.createToolTip();
                msg.setFont(new Font("Candara", Font.PLAIN , 16));
                final JDialog dlg  = msg.createDialog("Welcome " +getuser);
                dlg.setFont(new Font("Candara", Font.PLAIN , 16));
                dlg.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                msg.setBackground(new Color(207,208,210,200));
                dispose();
                
                Thread t = new Thread(new Runnable() {
                       @Override
                       public void run() {

                  Cms h = new Cms();
                
                  h.setVisible(true);
                dlg.setVisible(true);
                  h.setAlwaysOnTop(false);
h.login.setText(getuser);                  

                       }
                });
                t.start();
                             }
                
                
                
        }                
            } catch (Exception e) {
            }
           
           
           
           
           
           
           
       }
        
        } catch (Exception e) {
        e.printStackTrace();
        }

                break;
        }
    }//GEN-LAST:event_passtextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    public javax.swing.JPasswordField passtext;
    private javax.swing.JLabel password;
    private javax.swing.JLabel username;
    public javax.swing.JTextField usertext;
    // End of variables declaration//GEN-END:variables
}
