/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Locale;
/**
 *
 * @author User
 */
public class Calculat extends javax.swing.JFrame {

    //Variables
   //int clearDouble;
    int firstnumber;
    int secondnumber;
    int result;
    String operators;
    ArrayList<String> storage;
    static Point mousedrag;
String defualt; 
    
    /**
     * Creates new form Calculat
     */
    public Calculat() {
        initComponents();
        //this.setAlwaysOnTop(true);
        this.setEnabled(true);
        this.setLocation(400,200);
         input.setFocusable(true);
        //this.setExtendedState(MAXIMIZED_BOTH);
 mousedrag = null;
 defualt ="0";
 input.setText(defualt);
 javax.swing.JButton.setDefaultLocale(Locale.UK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        Display = new javax.swing.JTextField();
        BasicPanel = new javax.swing.JPanel();
        plus = new javax.swing.JLabel();
        minus = new javax.swing.JLabel();
        equals = new javax.swing.JLabel();
        divide = new javax.swing.JLabel();
        squareroot = new javax.swing.JLabel();
        multiply = new javax.swing.JLabel();
        dot = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        maximise = new javax.swing.JLabel();
        minimise = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        one = new javax.swing.JLabel();
        four = new javax.swing.JLabel();
        seven = new javax.swing.JLabel();
        eight = new javax.swing.JLabel();
        two = new javax.swing.JLabel();
        five = new javax.swing.JLabel();
        zero = new javax.swing.JLabel();
        three = new javax.swing.JLabel();
        six = new javax.swing.JLabel();
        nine = new javax.swing.JLabel();
        clearall = new javax.swing.JLabel();
        plusMinus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setUndecorated(true);
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });

        input.setEditable(false);
        input.setBackground(new java.awt.Color(255, 255, 255));
        input.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        input.setForeground(new java.awt.Color(0, 51, 51));
        input.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        input.setFocusCycleRoot(true);
        input.setFocusTraversalPolicyProvider(true);
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputKeyTyped(evt);
            }
        });

        Display.setEditable(false);
        Display.setBackground(new java.awt.Color(255, 226, 245));
        Display.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        Display.setForeground(new java.awt.Color(0, 153, 153));
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Display.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        BasicPanel.setBackground(jPanel1.getBackground());
        BasicPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        plus.setBackground(new java.awt.Color(102, 102, 102));
        plus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plus.setForeground(new java.awt.Color(236, 232, 232));
        plus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plus.setText("+");
        plus.setOpaque(true);
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plusMouseExited(evt);
            }
        });

        minus.setBackground(new java.awt.Color(102, 102, 102));
        minus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minus.setForeground(new java.awt.Color(236, 232, 232));
        minus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minus.setText("-");
        minus.setOpaque(true);
        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minusMouseExited(evt);
            }
        });

        equals.setBackground(new java.awt.Color(102, 102, 102));
        equals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        equals.setForeground(new java.awt.Color(236, 232, 232));
        equals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equals.setText("=");
        equals.setOpaque(true);
        equals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equalsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equalsMouseExited(evt);
            }
        });

        divide.setBackground(new java.awt.Color(102, 102, 102));
        divide.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        divide.setForeground(new java.awt.Color(236, 232, 232));
        divide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        divide.setText("÷");
        divide.setOpaque(true);
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                divideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                divideMouseExited(evt);
            }
        });

        squareroot.setBackground(new java.awt.Color(102, 102, 102));
        squareroot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        squareroot.setForeground(new java.awt.Color(236, 232, 232));
        squareroot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        squareroot.setText("√");
        squareroot.setOpaque(true);
        squareroot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                squarerootMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                squarerootMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                squarerootMouseExited(evt);
            }
        });

        multiply.setBackground(new java.awt.Color(102, 102, 102));
        multiply.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        multiply.setForeground(new java.awt.Color(236, 232, 232));
        multiply.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multiply.setText("X");
        multiply.setOpaque(true);
        multiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiplyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiplyMouseExited(evt);
            }
        });

        dot.setBackground(new java.awt.Color(102, 102, 102));
        dot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dot.setForeground(new java.awt.Color(236, 232, 232));
        dot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dot.setText(".");
        dot.setOpaque(true);
        dot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dotMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BasicPanelLayout = new javax.swing.GroupLayout(BasicPanel);
        BasicPanel.setLayout(BasicPanelLayout);
        BasicPanelLayout.setHorizontalGroup(
            BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BasicPanelLayout.createSequentialGroup()
                        .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(squareroot, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        BasicPanelLayout.setVerticalGroup(
            BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BasicPanelLayout.createSequentialGroup()
                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BasicPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(squareroot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Forward_40px.png"))); // NOI18N
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Clear Symbol_30px_3.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Time_25px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Basic Calculator");

        clear.setBackground(new java.awt.Color(102, 102, 102));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        clear.setForeground(new java.awt.Color(153, 153, 153));
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("C");
        clear.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        clear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear.setOpaque(true);
        clear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel4MouseReleased(evt);
            }
        });

        close.setBackground(new java.awt.Color(204, 204, 204));
        close.setForeground(new java.awt.Color(204, 204, 204));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete_20px_1.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        maximise.setBackground(new java.awt.Color(204, 204, 204));
        maximise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Unchecked Checkbox_20px.png"))); // NOI18N
        maximise.setEnabled(false);
        maximise.setOpaque(true);

        minimise.setBackground(new java.awt.Color(204, 204, 204));
        minimise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Minus Math _20px.png"))); // NOI18N
        minimise.setToolTipText("minimise");
        minimise.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimise.setIconTextGap(20);
        minimise.setOpaque(true);
        minimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimiseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimiseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimiseMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calc.png"))); // NOI18N
        jLabel2.setText("AceCalc");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimise, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(maximise, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addComponent(maximise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        one.setBackground(new java.awt.Color(102, 102, 102));
        one.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        one.setForeground(new java.awt.Color(236, 232, 232));
        one.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        one.setText("7");
        one.setOpaque(true);
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oneMouseExited(evt);
            }
        });

        four.setBackground(new java.awt.Color(102, 102, 102));
        four.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        four.setForeground(new java.awt.Color(236, 232, 232));
        four.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        four.setText("4");
        four.setOpaque(true);
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fourMouseExited(evt);
            }
        });

        seven.setBackground(new java.awt.Color(102, 102, 102));
        seven.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seven.setForeground(new java.awt.Color(236, 232, 232));
        seven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seven.setText("1");
        seven.setOpaque(true);
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sevenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sevenMouseExited(evt);
            }
        });

        eight.setBackground(new java.awt.Color(102, 102, 102));
        eight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eight.setForeground(new java.awt.Color(236, 232, 232));
        eight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eight.setText("2");
        eight.setOpaque(true);
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eightMouseExited(evt);
            }
        });

        two.setBackground(new java.awt.Color(102, 102, 102));
        two.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        two.setForeground(new java.awt.Color(236, 232, 232));
        two.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        two.setText("8");
        two.setOpaque(true);
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                twoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                twoMouseExited(evt);
            }
        });

        five.setBackground(new java.awt.Color(102, 102, 102));
        five.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        five.setForeground(new java.awt.Color(236, 232, 232));
        five.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        five.setText("5");
        five.setOpaque(true);
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fiveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fiveMouseExited(evt);
            }
        });

        zero.setBackground(new java.awt.Color(102, 102, 102));
        zero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        zero.setForeground(new java.awt.Color(236, 232, 232));
        zero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zero.setText("0");
        zero.setOpaque(true);
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                zeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                zeroMouseExited(evt);
            }
        });

        three.setBackground(new java.awt.Color(102, 102, 102));
        three.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        three.setForeground(new java.awt.Color(236, 232, 232));
        three.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        three.setText("9");
        three.setOpaque(true);
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                threeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                threeMouseExited(evt);
            }
        });

        six.setBackground(new java.awt.Color(102, 102, 102));
        six.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        six.setForeground(new java.awt.Color(236, 232, 232));
        six.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        six.setText("6");
        six.setOpaque(true);
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sixMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sixMouseExited(evt);
            }
        });

        nine.setBackground(new java.awt.Color(102, 102, 102));
        nine.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nine.setForeground(new java.awt.Color(236, 232, 232));
        nine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nine.setText("3");
        nine.setOpaque(true);
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nineMouseExited(evt);
            }
        });

        clearall.setBackground(new java.awt.Color(102, 102, 102));
        clearall.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearall.setForeground(new java.awt.Color(236, 232, 232));
        clearall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clearall.setText("CE");
        clearall.setOpaque(true);
        clearall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearallMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearallMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearallMouseExited(evt);
            }
        });

        plusMinus.setBackground(new java.awt.Color(102, 102, 102));
        plusMinus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plusMinus.setForeground(new java.awt.Color(236, 232, 232));
        plusMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plusMinus.setText("±");
        plusMinus.setOpaque(true);
        plusMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusMinusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plusMinusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plusMinusMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(plusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(one, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clearall, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BasicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(BasicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(clearall, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(200, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_inputActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DisplayActionPerformed

    
    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nextMouseClicked

    private void inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputKeyTyped
        // TODO add your handling code here:
        try{
        char e = evt.getKeyChar();
        
    if(!(Character.isDigit(e)|| (e==KeyEvent.VK_BACK_SPACE)
                || (e==KeyEvent.VK_DELETE)))
        {
        getToolkit().beep();
        evt.consume();
        }
      if(Character.isDigit(e))
        {
        String keys = String.valueOf(evt.getKeyChar());
        input.setText(input.getText()+keys);
        }
        }catch(Exception e){}        
    }//GEN-LAST:event_inputKeyTyped

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimiseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseMouseEntered
minimise.setBackground(new Color(204,220,220));
    }//GEN-LAST:event_minimiseMouseEntered

    private void minimiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseMouseClicked
this.setState(ICONIFIED);
    }//GEN-LAST:event_minimiseMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
      
      close.setBackground(new Color(110,130,130));
    close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete_20px_3.png")));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
close.setBackground(new Color(204,204,204));
close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete_20px_1.png")));
    }//GEN-LAST:event_closeMouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased

    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost

    }//GEN-LAST:event_jPanel1FocusLost

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

    }//GEN-LAST:event_formFocusLost

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
   jPanel4.setBackground(new Color(255,255,255));
    minimise.setBackground(new Color(255,255,255));
     close.setBackground(new Color(255,255,255));
      maximise.setBackground(new Color(255,255,255));
           jLabel2.setForeground(new Color(150,150,150));     
    }//GEN-LAST:event_formWindowLostFocus

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        String bsp = null;
        if(input.getText().length() >0)
        {
            StringBuilder strB = new StringBuilder(input.getText());
            
            strB.deleteCharAt(input.getText().length() -  1);
            bsp = strB.toString();            
            input.setText(bsp);            
if(input.getText().isEmpty()){
            input.setText(defualt);
repaint();
}
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Clear Symbol_30px_2.png")));
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Clear Symbol_30px_3.png")));
    }//GEN-LAST:event_deleteMouseExited

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        try {
            input.setText("0");
Display.setText("");
            firstnumber=0;
        secondnumber=0;
        if(storage.isEmpty()){
                storage.removeAll(storage);
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
clear.setBackground(new Color(83,83,83));
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
     clear.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_clearMouseExited

    private void minimiseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseMouseExited
      minimise.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_minimiseMouseExited

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
mousedrag=evt.getPoint();
this.setCursor(Cursor.MOVE_CURSOR);
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseReleased
 mousedrag=null;
this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_jPanel4MouseReleased

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
Point currentdrag = evt.getLocationOnScreen();
this.setLocation(currentdrag.x - mousedrag.x,currentdrag.y-mousedrag.y);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jPanel4.setBackground(new Color(204,204,204));
        minimise.setBackground(new Color(204,204,204));
        close.setBackground(new Color(204,204,204));
           maximise.setBackground(new Color(204,204,204));

 jLabel2.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_formWindowGainedFocus

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
              firstnumber = Integer.parseInt(input.getText());
              secondnumber = Integer.parseInt(input.getText());
              
        if(input.getText().startsWith(defualt,0))
      {
input.setText("");
          input.setText(input.getText()+one.getText());
      }          
      else{    if(Display.getText().startsWith(String.valueOf(firstnumber),0)){
                       // firstnumber=0;
                            input.setText(""); 
                                input.setText(input.getText()+one.getText());
                                
                        }else{
          input.setText(input.getText() 
                  +one.getText());
          }
      }

    }//GEN-LAST:event_oneMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
        // TODO add your handling code here:
            if(input.getText().startsWith(defualt,0))
      {
input.setText("");
 input.setText(input.getText()+four.getText());
      }          
      else{       
                if(Display.getText().startsWith(String.valueOf(firstnumber)) ){
                 //       firstnumber=0;
                            input.setText("");
                                input.setText(input.getText()+four.getText());
                        }else{
        input.setText(input.getText()+four.getText());
      }}

    }//GEN-LAST:event_fourMouseClicked

    private void sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseClicked
        // TODO add your handling code here:
                    if(input.getText().startsWith(defualt,0))
      {
input.setText("");
 input.setText(input.getText()+seven.getText());
      }          
      else{
                        if(Display.getText().startsWith(String.valueOf(firstnumber)) ){
                    //    firstnumber=0;
                            input.setText("");
                                input.setText(input.getText()+seven.getText());
                        }else{
                            
        input.setText(input.getText()+seven.getText());
                        }

      }

    }//GEN-LAST:event_sevenMouseClicked

    private void zeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseClicked
        // TODO add your handling code here:
                  if(input.getText().startsWith(defualt,0))
      {
input.setText("");
 input.setText(input.getText()+zero.getText());
      }          
      else{       
        input.setText(input.getText()+zero.getText());
      }

    }//GEN-LAST:event_zeroMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
        // TODO add your handling code here:
                firstnumber = Integer.parseInt(input.getText());
         if(input.getText().startsWith(defualt,0))
      {
input.setText("");
 input.setText(input.getText()+two.getText());
      }          
      else{       
             
                        if(Display.getText().startsWith(String.valueOf(firstnumber)) ){
                      firstnumber=0;
                            input.setText("");
                                input.setText(input.getText()+two.getText());
                                                
                        }else{
        input.setText(input.getText()+two.getText());
                             }

      }

    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
        // TODO add your handling code here:
            if(input.getText().startsWith(defualt,0))
      {
input.setText("");
 input.setText(input.getText()+three.getText());
      }          
      else{       
                if(Display.getText().startsWith(String.valueOf(firstnumber)) ){
                 //       firstnumber=0;
                            input.setText("");
                                input.setText(input.getText()+three.getText());
                        }else{
        input.setText(input.getText()+three.getText());
      }}

    }//GEN-LAST:event_threeMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
        // TODO add your handling code here:
             if(input.getText().startsWith(defualt,0))
      {
input.setText("");
 input.setText(input.getText()+five.getText());
      }          
      else{
                 if(Display.getText().startsWith(String.valueOf(firstnumber)) ){
                 //       firstnumber=0;
                            input.setText("");
                                input.setText(input.getText()+five.getText());
                        }else{
        input.setText(input.getText()+five.getText());
      }}

    }//GEN-LAST:event_fiveMouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
      if(input.getText().startsWith(defualt,0))
      {
input.setText("");
          input.setText(input.getText()+six.getText());
      }          
      else{       
          if(Display.getText().startsWith(String.valueOf(firstnumber)) ){
                    //    firstnumber=0;
                            input.setText("");
                                input.setText(input.getText()+six.getText());
                        }else{
          input.setText(input.getText()+six.getText());
      }}
    }//GEN-LAST:event_sixMouseClicked

    private void plusMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMinusMouseClicked
        // TODO add your handling code here:
        try{
        double pm = Double.parseDouble(String.valueOf(input.getText()));
        pm = pm *(-1);
        input.setText(String.valueOf(pm));
        }catch(Exception e){}
    }//GEN-LAST:event_plusMinusMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
              if(input.getText().startsWith(defualt,0))
      {
input.setText("");
 input.setText(input.getText()+eight.getText());
      }          
      else{       if(Display.getText().startsWith(String.valueOf(firstnumber)) ){
                     //   firstnumber=0;
                            input.setText("");
                                input.setText(input.getText()+eight.getText());
                        }else{
        input.setText(input.getText()+eight.getText());
      }
    }
    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
                 if(input.getText().startsWith(defualt,0))
      {
input.setText("");
 input.setText(input.getText()+nine.getText());
      }          
      else{       if(Display.getText().startsWith(String.valueOf(firstnumber)) ){
                      //  firstnumber=0;
                            input.setText("");
                                input.setText(input.getText()+nine.getText());
                        }else{
        input.setText(input.getText()+nine.getText());
      }}

    }//GEN-LAST:event_nineMouseClicked

    private void clearallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearallMouseClicked
        // TODO add your handling code here:
        try {
         
        input.setText(defualt);
        Display.setText(Display.getText());
        
        } catch (Exception e) {
        }
    }//GEN-LAST:event_clearallMouseClicked

    private void plusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseClicked
        // TODO add your handling code here:
        try{
            
            StringBuilder d = new StringBuilder(Display.getText());
                            StringBuilder s = new StringBuilder(Display.getText());
                            
            firstnumber = Integer.parseInt(input.getText());
         secondnumber = Integer.parseInt(input.getText());

         d.append(firstnumber);
         s.append(secondnumber);
         
         
         if(input.getText().startsWith(defualt,0))
      {
         input.setText("0");
      }          
      else{
             Display.setText(firstnumber+" "+plus.getText()); 
         operators=("+");
      
}

        
        
        }catch(Exception e){}
     
    }//GEN-LAST:event_plusMouseClicked

    private void minusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseClicked
        // TODO add your handling code here:
        firstnumber = Integer.parseInt(input.getText());
        try{
                          if(input.getText().startsWith(defualt,0))
      {
         input.setText("0");
      }          
      else{           
        Display.setText(firstnumber+" "+minus.getText());
         operators=("-");
      }
            
     
        }catch(Exception e){}
    }//GEN-LAST:event_minusMouseClicked

    private void equalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalsMouseClicked
        try{
           
        String answer;
   storage = new ArrayList<>();
         secondnumber = Integer.parseInt(input.getText());
         
        if( null != operators)switch (operators) {
                case "+":
                    //input.setText("");
                    result = firstnumber + secondnumber;
                    answer = String.format("%s", result);
                    //          Display.setText("");
                    Display.setText(answer);
                    storage.add(answer);
                    break;
                case "-":
                    // input.setText("");
                    result = firstnumber - secondnumber;
                    answer = String.format("%s", result);
                    //     Display.setText("");
                    Display.setText(answer);
                    storage.add(answer);
                    break;
                case "*":
                    //         input.setText("");
                    result = firstnumber * secondnumber;
                    answer = String.format("%s", result);
                    //    Display.setText("");
                    Display.setText(answer);
                    storage.add(answer);
                    break;
                case "÷":
                    // input.setText("");
                    result = firstnumber / secondnumber ;
                    answer = String.format("%s", result );
                    //     Display.setText("");
                    Display.setText(answer);
                    storage.add(answer);
                    break;
                case "%":
                    // input.setText("");
                    result = firstnumber % secondnumber;
                    answer = String.format("%s", result);
                    //       Display.setText("");
                    Display.setText(answer);
                    storage.add(answer);
                    break;
                default:
                    break;
            }
        }catch(NumberFormatException e)
        {}        

    }//GEN-LAST:event_equalsMouseClicked

    private void divideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseClicked
  try{
            firstnumber = Integer.parseInt(input.getText());
         if(input.getText().startsWith(defualt,0))
      {
         input.setText("0");
      }          
      else{       
        Display.setText(firstnumber+" "+divide.getText());
         operators=("÷");  
         }
      
  }catch(NumberFormatException e){}

    }//GEN-LAST:event_divideMouseClicked

    private void squarerootMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squarerootMouseClicked
        try{
           if(input.getText().startsWith(defualt,0))
      {
         input.setText("0");
      }          
      else{   
            
                double pm = Double.parseDouble(String.valueOf(input.getText()));
        pm = Math.sqrt(pm);
        input.setText(String.valueOf(pm));
        Display.setText("√"+"("+input.getText()+")");
         
         }
        
        }catch(Exception e){}
    }//GEN-LAST:event_squarerootMouseClicked

    private void multiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyMouseClicked
        firstnumber = Integer.parseInt(input.getText());        

        if(input.getText().startsWith(defualt,0))
      {
         input.setText("0");
      }          
      else{
        Display.setText(firstnumber+" "+multiply.getText());
         operators=("*");
      }
     

    }//GEN-LAST:event_multiplyMouseClicked

    private void dotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotMouseClicked
        try{
            if(input.getText().startsWith(defualt,0))
      {
         input.setText("0");
      }          
      else{
        if(! input.getText().contains("."))
        {
            
        input.setText(input.getText() + dot.getText());
        }
         }
      
        }catch(Exception e){}
    }//GEN-LAST:event_dotMouseClicked

    private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped

    }//GEN-LAST:event_jPanel1KeyTyped

    private void oneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseEntered
one.setBackground(new Color(155,155,155));
one.setForeground(new Color(33,33,33));
    }//GEN-LAST:event_oneMouseEntered

    private void oneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseExited
one.setBackground(new Color(102,102,102));
one.setForeground(new Color(236,232,232));
    }//GEN-LAST:event_oneMouseExited

    private void twoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseEntered
two.setBackground(new Color(155,155,155));
two.setForeground(new Color(33,33,33));
        // TODO add your handling code here:
    }//GEN-LAST:event_twoMouseEntered

    private void twoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseExited
two.setBackground(new Color(102,102,102));
two.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_twoMouseExited

    private void threeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseEntered
three.setBackground(new Color(155,155,155));
three.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_threeMouseEntered

    private void threeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseExited
 three.setBackground(new Color(102,102,102));
three.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_threeMouseExited

    private void fourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseEntered
four.setBackground(new Color(155,155,155));
four.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_fourMouseEntered

    private void fourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseExited
four.setBackground(new Color(102,102,102));
four.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_fourMouseExited

    private void fiveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseEntered
five.setBackground(new Color(155,155,155));
five.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_fiveMouseEntered

    private void fiveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseExited
five.setBackground(new Color(102,102,102));
five.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_fiveMouseExited

    private void sixMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseEntered
six.setBackground(new Color(155,155,155));
six.setForeground(new Color(33,33,33));


    }//GEN-LAST:event_sixMouseEntered

    private void sixMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseExited
six.setBackground(new Color(102,102,102));
six.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_sixMouseExited

    private void sevenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseEntered
seven.setBackground(new Color(155,155,155));
seven.setForeground(new Color(33,33,33));


    }//GEN-LAST:event_sevenMouseEntered

    private void eightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseEntered
eight.setBackground(new Color(155,155,155));
eight.setForeground(new Color(33,33,33));


    }//GEN-LAST:event_eightMouseEntered

    private void eightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseExited
eight.setBackground(new Color(102,102,102));
eight.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_eightMouseExited

    private void sevenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseExited
seven.setBackground(new Color(102,102,102));
seven.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_sevenMouseExited

    private void nineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseEntered
nine.setBackground(new Color(155,155,155));
nine.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_nineMouseEntered

    private void nineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseExited
nine.setBackground(new Color(102,102,102));
nine.setForeground(new Color(236,232,232));
    }//GEN-LAST:event_nineMouseExited

    private void plusMinusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMinusMouseEntered
plusMinus.setBackground(new Color(155,155,155));
plusMinus.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_plusMinusMouseEntered

    private void plusMinusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMinusMouseExited
plusMinus.setBackground(new Color(102,102,102));
plusMinus.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_plusMinusMouseExited

    private void zeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseEntered
zero.setBackground(new Color(155,155,155));
zero.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_zeroMouseEntered

    private void zeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseExited
zero.setBackground(new Color(102,102,102));
zero.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_zeroMouseExited

    private void clearallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearallMouseEntered
clearall.setBackground(new Color(155,155,155));
clearall.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_clearallMouseEntered

    private void clearallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearallMouseExited
clearall.setBackground(new Color(102,102,102));
clearall.setForeground(new Color(236,232,232));
    }//GEN-LAST:event_clearallMouseExited

    private void plusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseEntered
plus.setBackground(new Color(155,155,155));
plus.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_plusMouseEntered

    private void plusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseExited
plus.setBackground(new Color(102,102,102));
plus.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_plusMouseExited

    private void minusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseEntered
minus.setBackground(new Color(155,155,155));
minus.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_minusMouseEntered

    private void minusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseExited
minus.setBackground(new Color(102,102,102));
minus.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_minusMouseExited

    private void equalsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalsMouseEntered
        // TODO add your handling code here:
        equals.setBackground(new Color(155,155,155));
equals.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_equalsMouseEntered

    private void equalsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalsMouseExited
        // TODO add your handling code here:
        equals.setBackground(new Color(102,102,102));
equals.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_equalsMouseExited

    private void divideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseEntered
divide.setBackground(new Color(155,155,155));
divide.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_divideMouseEntered

    private void divideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseExited
divide.setBackground(new Color(102,102,102));
divide.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_divideMouseExited

    private void squarerootMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squarerootMouseEntered
squareroot.setBackground(new Color(155,155,155));
squareroot.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_squarerootMouseEntered

    private void squarerootMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squarerootMouseExited
        // TODO add your handling code here:
        squareroot.setBackground(new Color(102,102,102));
squareroot.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_squarerootMouseExited

    private void multiplyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyMouseEntered
multiply.setBackground(new Color(155,155,155));
multiply.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_multiplyMouseEntered

    private void multiplyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyMouseExited
        // TODO add your handling code here:
        multiply.setBackground(new Color(102,102,102));
multiply.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_multiplyMouseExited

    private void dotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotMouseEntered
dot.setBackground(new Color(155,155,155));
dot.setForeground(new Color(33,33,33));

    }//GEN-LAST:event_dotMouseEntered

    private void dotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotMouseExited
        // TODO add your handling code here:
        dot.setBackground(new Color(102,102,102));
dot.setForeground(new Color(236,232,232));

    }//GEN-LAST:event_dotMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasicPanel;
    private javax.swing.JTextField Display;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel clearall;
    private javax.swing.JLabel close;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel divide;
    private javax.swing.JLabel dot;
    private javax.swing.JLabel eight;
    private javax.swing.JLabel equals;
    private javax.swing.JLabel five;
    private javax.swing.JLabel four;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel maximise;
    private javax.swing.JLabel minimise;
    private javax.swing.JLabel minus;
    private javax.swing.JLabel multiply;
    private javax.swing.JLabel next;
    private javax.swing.JLabel nine;
    private javax.swing.JLabel one;
    private javax.swing.JLabel plus;
    private javax.swing.JLabel plusMinus;
    private javax.swing.JLabel seven;
    private javax.swing.JLabel six;
    private javax.swing.JLabel squareroot;
    private javax.swing.JLabel three;
    private javax.swing.JLabel two;
    private javax.swing.JLabel zero;
    // End of variables declaration//GEN-END:variables

}
